### ISSUE TITLE
When AVR is manually powered on/off the power state tag is not updated  

### ISSUE THREAD

**Issue by jeroenvano** [murderbeard/com.moz.denon#1]
Hi Ralph, 

Kind of a feature request, not a real issue ...

I noticed that the power state tag is only changed when the AVR power state has been set by Homey (e.g. a flow). My AVR is powered on/off manually directly most of the times by my family that does not update the tag in Homey. Is it possible that Homey gets notified of a power change or a changed channel when this is done manually on the AVR that updates tags? Depending on power state of the zones (main, zone2, zone3) or set channels better flow conditions can be used for advanced scenarios.

Regards,
Jeroen

**Comment by murderbeard** [comment]
Hi Jeroen,

I didn't get notified that an issue was added here so sorry for the late reply. It's true that there is no checking being done by the app to see if the device has changed state, might be an idea to add that as part of the default app behaviour.

I think one thing you can try is to create a new flow that runs every X seconds and uses the "Powered On?" flow card, this should update the on/off data.

Same can apply to detect any channel changes, but there's no way to check what the previous channel was so it would be kind of spammy to keep checking that; but perhaps that can work temporarily as a work around. Together with keeping some flow variable to remember what channel it used to be. Then again that's probably not much fun to build.

Is this still something you're interested in having? Might look into this for a future release.

Regards,
Ralph

**Comment by jeroenvano** [comment]
Hi Ralph,

Thanks for your reply and update. I already use the every x seconds check
for power on status. It works but would be nicer if it was build in the
app.

I havent build the check active channel flows as it would need a lot of
flows if you also want to upfate a logic variable with the acive channel.
Still this would be nice to have. Also for active volume level checking.

I am not sure if build in the app you have to pull the info from the tuner
all the time or if changes can also be pushed. Looking to the denon app it
gets updated as soon as something changes.

Thanks so far I like the app :)

Regards
Jeroen

Op 2 okt. 2017 12:28 schreef "murderbeard" <notifications@github.com>:

Hi Jeroen,

I didn't get notified that an issue was added here so sorry for the late
reply. It's true that there is no checking being done by the app to see if
the device has changed state, might be an idea to add that as part of the
default app behaviour.

I think one thing you can try is to create a new flow that runs every X
seconds and uses the "Powered On?" flow card, this should update the on/off
data.

Same can apply to detect any channel changes, but there's no way to check
what the previous channel was so it would be kind of spammy to keep
checking that; but perhaps that can work temporarily as a work around.
Together with keeping some flow variable to remember what channel it used
to be. Then again that's probably not much fun to build.

Is this still something you're interested in having? Might look into this
for a future release.

Regards,
Ralph

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/murderbeard/com.moz.denon/issues/1#issuecomment-333497168>,
or mute the thread

**Comment by murderbeard** [comment]
(Feature was added in v1.1.0, Feb 2020)
