### ISSUE TITLE
Denon AVR-X4500H confirmed working

### ISSUE THREAD

**Issue by provanguard** [murderbeard/com.moz.denon#14]
I have configured some flows that send custom commands to the receiver, using commands found in the following spread sheet:

[FY21AVR_DENON_PROTOCOL_V02_04062020.xlsx](https://github.com/murderbeard/com.moz.denon/files/7823396/FY21AVR_DENON_PROTOCOL_V02_04062020.xlsx)

So far so good :)

**Comment by murderbeard** [comment]
Thanks for the info! The X4500H will be included in the supported list in a future release.
