### ISSUE TITLE
Migrating to SDK3 and Marantz support

### ISSUE THREAD

**Issue by powermarcel10** [murderbeard/com.moz.denon#15]
Hi!

I'm having a question. As Homey Pro 2023 will only support SDK3 apps, I am wondering if you will update your app to this new standard.

Athom says that it is really simple to upgrade apps from SDK2 to SDK3, so I hope you will. 🤗

I am using a Marantz receiver, and had some contact with the developer of the Marantz app for Homey. He stopped using Homey so that app is not supported anymore.

However, I tried your app and it is working the same. So, Marantz is also supported by your app. Maybe you can rename your app to Denon/Marantz. This may be lead to a bigger install base for your app. 👍🏻

Cheers en best regards,
Marcel

**Comment by murderbeard** [comment]
Hi Marcel,

Thanks for reaching out. The app has already been updated to sdk3 for my own local installation and is stable, so I'll be publishing it soon to the athom/homey store. It's too bad athom didn't indicate the deprecation of sdk2 sooner, then I'd have updated the app before the announcement. Now people might think the app development is dead.

Thanks for the tip about the Marantz thing, I'll look into it. Do you have the model number of your receiver? I can check if I find some documentation on their Telnet protocol.

Best regards,
Ralph

**Comment by pjmpessers** [comment]
> Hi Marcel,
> 
> Thanks for reaching out. The app has already been updated to sdk3 for my own local installation and is stable, so I'll be publishing it soon to the athom/homey store. It's too bad athom didn't indicate the deprecation of sdk2 sooner, then I'd have updated the app before the announcement. Now people might think the app development is dead.
> 
> Thanks for the tip about the Marantz thing, I'll look into it. Do you have the model number of your receiver? I can check if I find some documentation on their Telnet protocol.
> 
> Best regards, Ralph

Great to hear, Ralph. Thank you.

**Comment by murderbeard** [comment]
Thanks guys. A new version has been submitted to Athom and should be coming online soon. I'm guessing it will automatically remove the warning on the app store page about not being supported on the upcoming Homey Pro.

**Comment by pjmpessers** [comment]
That is great to hear. Thanks. 👍🏻



Verzonden vanaf mijn Galaxy



-------- Oorspronkelijk bericht --------
Van: murderbeard ***@***.***>
Datum: 03-11-2022 10:14 (GMT+01:00)
Aan: "murderbeard/com.moz.denon" ***@***.***>
Cc: Pieter ***@***.***>, Comment ***@***.***>
Onderwerp: Re: [murderbeard/com.moz.denon] Migrating to SDK3 and Marantz support (Issue #15)


Thanks guys. A new version has been submitted to Athom and should be coming online soon. I'm guessing it will automatically remove the warning on the app store page about not being supported on the upcoming Homey Pro.
