### ISSUE TITLE
App stopped working

### ISSUE THREAD

**Issue by provanguard** [murderbeard/com.moz.denon#17]
Really not sure where the problem is yet, but Homey Pro 2019 no longer can communicate with my Denon 4500H. Seems like the requests are timing out. I can access the web interface for Denon and the IP is the same like configured in Homey for the app.
What is the best way to debug?

**Comment by murderbeard** [comment]
Hi, this is the second time I hear about timeout errors for Homey Pro 2019. Unfortunately at the same time as the last update Athom pushed an update to Homey so it's unclear if it's the app or homey itself. And just to be sure, the app worked normally before the updates, yes?

I myself don't own a HP2019 do can't do any proper testing from here so I'll have to figure it out remotely. Or get someone to debug run the app on a HP2019 but that requires some setting up to do. Is that something you're comfortable doing perhaps?

And do you have advanced flows by any change? If so, if you haven't tried already, you can get the specific error from a failed request this way. It would probably just say something about a timeout.
![image](https://github.com/murderbeard/com.moz.denon/assets/23704547/aa267650-5af6-4b0b-b3f3-f3c98c2fef96)

I'm thinking of making a test version available that contains a flow card that forcibly crashes the app so I can get a debug log from someone. Or one that just keeps the entire log of the app in memory and add a flow card that logs it to somewhere.

Hope we can figure this out soon,
~ Ralph

**Comment by provanguard** [comment]
I am still on software version 8,1.4. I haven't updated to the latest 8.1.5. Is that version required by the app?

I managed to capture the moment the error was reported. It happened after few minutes since the flow was started by the Test button.

App failed to respond error message:

![capture_20230706_220438](https://github.com/murderbeard/com.moz.denon/assets/19497436/e24882b6-641c-4ae2-8990-6682174a160c)

**Comment by murderbeard** [comment]
Thanks for the info. No the app should work fine on that version. I think the timeout message at the bottom is homey reporting the app is not responding but somehow not crashing.

What does the red triangle in the card show when you hover over it? I think that should show the error message.

In the mean time I'm digging out my old Homey Pro 2013 and see if it shows similar issues.

**Comment by provanguard** [comment]
The red triangle just changes to ... when I hover over it. There is no extra message as far as I can tell.
I am on Homey Pro 2019, the round ball one :)

**Comment by provanguard** [comment]
OMG; I restarted the app through the mobile Homey app and the Denon app seems to work fine again :)
I am really sorry for the false alarm here.

**Comment by murderbeard** [comment]
And it stays working? Even when abusing it a bit, toggling somethings on and off?

If so it might be related to a bug I've had happen to my Homey Pro 2023, where the app after running for about a week would lose connection in a similar way.

**Comment by provanguard** [comment]
I will report back if the issue happens again. For the moment all is working fine. Thank you!
