### ISSUE TITLE
Add CD to DENON AVR

### ISSUE THREAD

**Issue by marcelkurvers** [murderbeard/com.moz.denon#2]
Hi Ralph

Excellent app, works fine with my DENON X4400H on main channels. It's a shame the CD channel is missing in the Cards. Is this easy to add?

Thanks

Marcel

**Comment by murderbeard** [comment]
Hi Marcel,

Strange that CD is missing from the list. My own receiver also has this channel; from which I initially used the documentation to create that list.  To add it a minor change.

At the moment you can change the channel manually by using the custom command card with the following command: SICD

Best regards,
Ralph

**Comment by mahendriks** [comment]
Hello Ralph,

Thanks for creating this app, it really works fine for me. On my AVR 2313 I have connected my chromecast audio to my CD input and it would be nice if this feature could be added in the future.  Meanwhile I will use the custom command.

Thanks!

**Comment by murderbeard** [comment]
CD is added to sources list in the upcoming version. Test version available [here](https://homey.app/nl-nl/app/com.moz.denon/Denon-AVR/test/).
